### PR TITLE
Add French Translation 🥖

### PR DESCRIPTION
**Pull request by TathanDev**

### CODE REVIEW

**Comment by AbsolemJackdaw** [comment]
There's a typo in splash potion

**Review by AbsolemJackdaw — CHANGES_REQUESTED** [review]
typo in splash

missing translation keys for axolotl potion

**Review by AbsolemJackdaw — COMMENTED** [review]
Splash potion in french is 'Potion Jetable' 
Potion a Simulation would be a better fit , rather then Potion de Simulateur

**Comment by TathanDev** [comment]
Yes i know. It's because in French, we don"t say "Potion Jetable", we use the english name. Like Items.
But i can fix this^^

**Review by AbsolemJackdaw — APPROVED** [review]

**Pull request merged**
